port: "80"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  password: "testpass"
  dbname: "postgres"
  sslmode: "disable"

  telegramBotToken : "5085408878:AAGMbrpXnjoJtZRYVYkKCvxeWYLfTztofHI"
  WebhookURL : "https://d381-81-23-5-2.eu.ngrok.io"