port: "8000"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  password: "testpass"
  dbname: "postgres"
  sslmode: "disable"

  telegramBotToken : "5085408878:AAGADVkl_llsCAh73UIbVH1fN4f9IcbGBYw"
